<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Website/Sign Up</title>

</head>
<body>
<h1>link for registration</h1>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiU47Ax7pVORfIQGq2c1D9-FGqJrd4NwGP-WRrp7ibkA&s">
<h2><a href="http://localhost:8080/confirm/${confirm_code}">For registration</a></h2>
</body>
</html>